In [2]:
import pandas as pd

In [15]:
df1 = pd.read_csv("../data/accounts.csv")
print(df1.isnull().sum())
print("Duplicate count:",df1.duplicated().sum())

account_id           0
customer_id          0
account_type         1
account_open_date    0
branch               0
account_status       0
opening_balance      0
dtype: int64
Duplicate count: 0

In [5]:
# Select rows where any column is missing
display(df1[df1.isnull().any(axis=1)])

,account_id,customer_id,account_type,account_open_date,branch,account_status,opening_balance
8,A200008,C100850,NaN,8/16/2023,T Nagar,Active,474965.13

In [10]:
df1['account_type'] = df1['account_type'].fillna('Current')
print(df1)

     account_id customer_id account_type account_open_date             branch  \
0       A200000     C100771     Business        12/25/2022        Mumbai Fort
1       A200001     C100057     Business          7/2/2024        Mumbai Fort
2       A200002     C101408      Current         10/3/2020  Bengaluru MG Road
3       A200003     C101837     Business         7/17/2024        Mumbai Fort
4       A200004     C101573      Savings        12/12/2019         Anna Nagar
...         ...         ...          ...               ...                ...
2395    A202395     C100309      Savings         11/5/2025    Chennai Central
2396    A202396     C101872      Savings         4/21/2019        Mumbai Fort
2397    A202397     C100425      Current         12/4/2019         Anna Nagar
2398    A202398     C101196      Current         8/18/2024        Mumbai Fort
2399    A202399     C101141      Savings         9/20/2021    Chennai Central

     account_status  opening_balance
0            Closed        565188.86
1           Dormant        533186.36
2            Active        507981.18
3            Active         22150.29
4            Active         52213.93
...             ...              ...
2395         Active        549589.74
2396         Active        562062.99
2397         Active        161559.46
2398         Active        298259.04
2399         Active        711478.97

[2400 rows x 7 columns]

In [16]:
print(df1.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
2395    False
2396    False
2397    False
2398    False
2399    False
Length: 2400, dtype: bool

In [17]:
df2 = pd.read_csv("../data/customers.csv")
print(df2.isnull().sum())
print("Duplicate count:",df2.duplicated().sum())

customer_id          0
customer_name        0
age                  0
gender               0
occupation           0
country              0
city                 0
customer_type        0
account_open_date    0
risk_rating          0
annual_income        0
dtype: int64
Duplicate count: 0

In [18]:
# Select rows where any column is missing
display(df2[df2.isnull().any(axis=1)])

Empty DataFrame
Columns: [customer_id, customer_name, age, gender, occupation, country, city, customer_type, account_open_date, risk_rating, annual_income]
Index: []

In [19]:
df3 = pd.read_csv("../data/alerts.csv")
print(df3.isnull().sum())
print("Duplicate count:",df3.duplicated().sum())

alert_id                0
transaction_id          0
customer_id             0
alert_type              0
alert_date              0
risk_score              0
alert_status            0
investigation_result    0
investigator            0
closure_date            0
dtype: int64
Duplicate count: 0

In [20]:
df4 = pd.read_csv("../data/transactions.csv")
print(df4.isnull().sum())
print("Duplicate count:",df4.duplicated().sum())

transaction_id         0
account_id             0
transaction_date       0
transaction_type       0
transaction_amount     0
transaction_channel    0
sender_country         0
receiver_country       0
merchant_category      0
beneficiary_id         0
transaction_status     0
device_id              0
ip_address             0
dtype: int64
Duplicate count: 0

In [21]:
df5 = pd.read_csv("../data/customers_kyc.csv")
print(df5.isnull().sum())
print("Duplicate count:",df5.duplicated().sum())

customer_id                     0
occupation                      0
source_of_funds                 0
expected_monthly_transaction    0
expected_transaction_country    0
kyc_status                      0
dtype: int64
Duplicate count: 0